-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.product
(
    product_id integer NOT NULL,
    product_category character varying(200) COLLATE pg_catalog."default",
    product_type character varying(200) COLLATE pg_catalog."default",
    price numeric,
    CONSTRAINT product_pkey PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public.product_type
(
    product_type character varying(200) COLLATE pg_catalog."default" NOT NULL,
    product_name character varying(200) COLLATE pg_catalog."default",
    description character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT product_type_pkey PRIMARY KEY (product_type)
);

CREATE TABLE IF NOT EXISTS public.sales_detail
(
    sales_outlet_id integer NOT NULL,
    customer_id integer,
    product_id integer,
    quantity integer,
    price numeric,
    CONSTRAINT sales_detail_pkey PRIMARY KEY (sales_outlet_id)
);

CREATE TABLE IF NOT EXISTS public.sales_transcations
(
    transaction_id integer NOT NULL,
    transaction_date date,
    transaction_time time without time zone,
    sales_outlet_id integer,
    staff_id integer,
    product_id integer,
    CONSTRAINT sales_transcations_pkey PRIMARY KEY (transaction_id)
);

ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT product_product_type_fkey FOREIGN KEY (product_type)
    REFERENCES public.product_type (product_type) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sales_transcations
    ADD CONSTRAINT sales_transcations_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.product (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sales_transcations
    ADD CONSTRAINT sales_transcations_sales_outlet_id_fkey FOREIGN KEY (sales_outlet_id)
    REFERENCES public.sales_detail (sales_outlet_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;